# Generated by Django 3.2.5 on 2021-07-05 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
